//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glav.PayMeBack.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtPaymentPlan
    {
        public System.Guid Id { get; set; }
        public System.Guid UserPaymentPlanId { get; set; }
        public System.Guid DebtId { get; set; }
        public int PaymentPeriod { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> ExpectedEndDate { get; set; }
        public Nullable<decimal> InitialPayment { get; set; }
        public Nullable<bool> IsOutstanding { get; set; }
        public System.Guid UserIdWhoOwesDebt { get; set; }
    
        public virtual UserPaymentPlan UserPaymentPlan { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual Debt Debt { get; set; }
    }
}
