//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glav.PayMeBack.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAuthToken
    {
        public long Id { get; set; }
        public string AccessToken { get; set; }
        public System.DateTime AccessTokenExpiry { get; set; }
        public string RefreshToken { get; set; }
        public System.DateTime RefreshTokenExpiry { get; set; }
        public System.Guid AssociatedUserId { get; set; }
        public string Scope { get; set; }
    }
}
