//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glav.PayMeBack.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPaymentPlan
    {
        public UserPaymentPlan()
        {
            this.DebtPaymentPlans = new HashSet<DebtPaymentPlan>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<DebtPaymentPlan> DebtPaymentPlans { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
