//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glav.PayMeBack.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public UserDetail()
        {
            this.Debts = new HashSet<Debt>();
            this.UserPaymentPlans = new HashSet<UserPaymentPlan>();
        }
    
        public System.Guid Id { get; set; }
        public string EmailAddress { get; set; }
        public string FirstNames { get; set; }
        public string Surname { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Debt> Debts { get; set; }
        public virtual ICollection<UserPaymentPlan> UserPaymentPlans { get; set; }
    }
}
