//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glav.PayMeBack.Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    
    public partial class PayMeBackEntities : DbContext
    {
        public PayMeBackEntities()
            : base("name=PayMeBackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<OAuthToken> OAuthTokens { get; set; }
        public DbSet<UsageLog> UsageLogs { get; set; }
        public DbSet<DebtDetail> DebtDetails { get; set; }
        public DbSet<UserPaymentPlanDetail> UserPaymentPlanDetails { get; set; }
        public DbSet<DebtPaymentInstallmentDetail> DebtPaymentInstallmentDetails { get; set; }
        public DbSet<UserDetail> UserDetails { get; set; }
        public DbSet<NotificationOptionsDetail> NotificationOptionsDetails { get; set; }
    
        public virtual ObjectResult<UserDetail> SearchUsers(string searchCriteria, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(UserDetail).Assembly);
    
            var searchCriteriaParameter = searchCriteria != null ?
                new ObjectParameter("searchCriteria", searchCriteria) :
                new ObjectParameter("searchCriteria", typeof(string));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserDetail>("SearchUsers", searchCriteriaParameter, pageNumberParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<UserDetail> SearchUsers(string searchCriteria, Nullable<int> pageNumber, Nullable<int> pageSize, MergeOption mergeOption)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(UserDetail).Assembly);
    
            var searchCriteriaParameter = searchCriteria != null ?
                new ObjectParameter("searchCriteria", searchCriteria) :
                new ObjectParameter("searchCriteria", typeof(string));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("pageNumber", pageNumber) :
                new ObjectParameter("pageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserDetail>("SearchUsers", mergeOption, searchCriteriaParameter, pageNumberParameter, pageSizeParameter);
        }
    }
}
