//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glav.PayMeBack.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsageLog
    {
        public long Id { get; set; }
        public bool IsRequest { get; set; }
        public System.DateTime TimeOfOperation { get; set; }
        public string HttpMethod { get; set; }
        public string ClientIdentifier { get; set; }
        public string Uri { get; set; }
        public string Body { get; set; }
        public Nullable<int> StatusCode { get; set; }
    }
}
